name:                selfcat
version:             0.1.2.0
homepage:            https://github.com/matsubara0507/selfcat#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/selfcat#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.4.9
- mix
- mix-plugin-github
- github
- aeson
- aeson-pretty
- text
- yaml

library:
  source-dirs: src

executables:
  selfcat:
    main: Main.hs
    source-dirs: app
    dependencies:
    - selfcat
    - gitrev
    - dotenv
