resolver: lts-13.20
packages:
- '.'
extra-deps:
- rio-0.1.9.2
- extensible-0.5
- github-0.21
- github: matsubara0507/mix.hs
  commit: a476a706aa2b319683cc4eba612897486f01e9ac
  subdirs:
  - mix
  - mix-plugin-github

docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: matsubara0507/selfcat
    base: matsubara0507/ubuntu-for-haskell
