resolver: lts-17.15
packages:
- '.'
extra-deps:
- extensible-0.8.2
- membership-0
- incremental-0.3.1
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-plugin-github

docker:
  repo: ghcr.io/matsubara0507/stack-build:18.04
  enable: false
